on:
  workflow_dispatch:
    inputs:
      linux_install_script_url:
        description: 'LINUX_INSTALL_SCRIPT_URL'
        required: true
        default: 'https://download.clojure.org/install/linux-install-1.10.1.727.sh'
      tags:
        description: 'comma separated'


jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ajchemist/clojure-cli
    strategy:
      matrix:
        cfg:
          - { context: clojure-cli/graalvm-ce, tags: [  ] }
    name: Context {{ matrix.cfg.context }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitLab Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - uses: actions/checkout@v2


      - name: Github inputs
        run: |
          echo "${{ github.event.inputs.linux_install_script_url }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "SHA: ${{ github.sha }}"
